server:
  port: 8087 #jenkins is using 8080 port
spring:
  application:
    name: esupa
  datasource:
    url: jdbc:postgresql://localhost:5432/esupa
    username: postgres # Use the dedicated user
    password: nguyen123 # Use a strong password
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        allow_jdbc_metadata_access: true
  jpa:
    show-sql: true # Set to false in production
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true # Set to false in production
        format_sql: true
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false # set to TRUE after releasing to production
    locations: classpath:db/migration
    baseline-on-migrate: true


#  kafka:
#    bootstrap-servers: localhost:9092
#    topic: KAFKA_TOPIC_FROM_ADMIN
#    consumer:
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer