spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # Create schema on startup, drop on shutdown for tests
    show-sql: true
  flyway:
    enabled: false # Usually disable Flyway for H2 test profile if ddl-auto is create-drop